safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"
      author: "Red Hat"

siteTitle: "Red Hat"
projectTitle: "Offliner"
title: "Offliner"
tagline: "Maven Repositories .... DOWNLOADED"
owner: "Red Hat"
ownerEmail: jdcasey@redhat.com

markdown: kramdown
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
